# Generated by Django 3.1.3 on 2020-11-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchcore', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttag',
            name='archetype',
            field=models.CharField(choices=[('C', 'Complexity'), ('T', 'Theme'), ('D', 'Technology'), ('L', 'Language')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='matchcore.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='matchcore.user'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='matchcore.project'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='matchcore.user'),
        ),
    ]
