# Generated by Django 3.1.3 on 2020-12-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchcore', '0006_auto_20201201_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='img',
            field=models.ImageField(upload_to='images/tags'),
        ),
    ]
