# Generated by Django 3.1.3 on 2020-12-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchcore', '0007_auto_20201201_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='', upload_to='images/users'),
        ),
    ]
