# Generated by Django 3.1.3 on 2020-12-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchcore', '0010_auto_20201201_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectparticipation',
            name='user',
        ),
        migrations.AddField(
            model_name='projectparticipation',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='matchcore.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='matchcore.person'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='matchcore.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(through='matchcore.ProjectParticipation', to='matchcore.Person'),
        ),
    ]
