# Generated by Django 3.1.3 on 2020-12-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchcore', '0011_auto_20201201_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='', upload_to='images/projects'),
        ),
    ]
