# Generated by Django 3.1.3 on 2020-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchcore', '0012_auto_20201202_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
