# Generated by Django 3.1.3 on 2020-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchcore', '0013_auto_20201203_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='interacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectparticipation',
            name='contribution',
            field=models.IntegerField(default=0),
        ),
    ]
